[build]
  edge_functions = "edge-functions"

[[edge_functions]]
  cache = "manual"
  path = "/date"
  function = "date"  

[[headers]]
  for = "/date"
  [headers.values]
  cache-control = "public, s-maxage=3600"